platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: UrlCheck

outputs:
- name: coverage-results

run:
  path: ./UrlCheck/ci/scripts/unit-test.sh
